### PR TITLE
Android Support

### PR DESCRIPTION
**Pull request by patmisch**

### CODE REVIEW

**Comment by HiteshR90** [comment]
I have integrated this in my app but after adding this app won't start. @patmisch do you have steps that needs to performed before linking this library for android ?

image

Here is what I have added in build.gradle file

**Comment by HiteshR90** [comment]
@patmisch and update on this ?

**Comment by HiteshR90** [comment]
@patmisch sure

**Comment by HiteshR90** [comment]
@patmisch new changes are properly integrated. However when I try to connect a reader process stops after StripeTerminal.getConnectionStatus().

`public class MainActivity extends ReactActivity {

    /**
     * Returns the name of the main component registered from JavaScript.
     * This is used to schedule rendering of the component.
     */

    private static final int REQUEST_CODE_LOCATION = 1;

    @Override
    protected String getMainComponentName() {
        return "StripeTerminalTest";
    }
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        SplashScreen.show(this);

        if (ContextCompat.checkSelfPermission(this,
                Manifest.permission.ACCESS_FINE_LOCATION) != PackageManager.PERMISSION_GRANTED) {
            String[] permissions = {Manifest.permission.ACCESS_FINE_LOCATION};
            // REQUEST_CODE_LOCATION should be defined on your app level
            ActivityCompat.requestPermissions(this, permissions, REQUEST_CODE_LOCATION);
        }

        super.onCreate(savedInstanceState);
    }

    @Override
    public void onRequestPermissionsResult(int requestCode, String[] permissions, int[] grantResults) {
        if (requestCode == REQUEST_CODE_LOCATION && grantResults.length > 0
                && grantResults[0] != PackageManager.PERMISSION_GRANTED) {
            throw new RuntimeException("Location services are required in order to " +
                    "connect to a reader.");
        }
    }
}`

this is my MainActivity class

**Comment by HiteshR90** [comment]
`import StripeTerminal from 'react-native-stripe-terminal';
import axios from 'axios';

import { getApiURL } from './actions';

const readerAPI = {
  discovering: false,
  isConnected: false,
  deviceName: '',
  paymentStatus: '',

  async intiStripeTerminal() {
    await StripeTerminal.initialize({
	fetchConnectionToken: () => {
	  const API_URL = getApiURL();
	  return axios
		.get(`${API_URL}/terminalConnection`)
		.then(resp => {
		  return resp.data.token;
		});
	},
  });
  },

  async getConnectionStatus() {
    const status = await StripeTerminal.getConnectionStatus();
    if (status === StripeTerminal.ConnectionStatusConnected) {
      this.isConnected = true;
      return 'CONNECTED';
    }
    if (status === StripeTerminal.ConnectionStatusConnecting) {
      this.discovering = true;
      return 'DISCOVERING';
    }
    if (status === StripeTerminal.ConnectionStatusNotConnected) {
      this.isConnected = false;
      return 'DISCONNECTED';
    }
  },

  async connectReader() {
	  const status = await StripeTerminal.getConnectionStatus();
	  if (status === StripeTerminal.ConnectionStatusConnected) {
		this.isConnected = true;
	  }
	  if (status === StripeTerminal.ConnectionStatusConnecting) {
		this.discovering = true;
		return;
	  }
	  try {
		this.discovering = true;
		await StripeTerminal.discoverReaders(
		  StripeTerminal.DeviceTypeChipper2X,
		  StripeTerminal.DiscoveryMethodBluetoothProximity,
		  true
		);
		this.isConnected = true;
	  } catch (err) {
		this.discovering = false;
		console.error('Error discovering readers', err);
		//Alert.alert('Card Reader Error', err.error)
		return;
	  }
	  this.discovering = false;
  },

  async readersDiscovered(readers) {
    if (!readers || !readers.length) return;
    const reader = readers[0];
    this.deviceName = reader.serialNumber;
    try {
      await StripeTerminal.connectReader(reader.serialNumber);
    } catch (err) {
      console.error('Error connecting reader', err);
      //Alert.alert('Card Reader Error', err.error)
      return;
    }
    this.textData = reader;
  },

  didReportUnexpectedReaderDisconnect() {
    //Alert.alert('Card Reader Error', 'The card reader has disconnected unexpectedly.  The software will try to reconnect.')
    this.isConnected = false;
    this.discoverReaders();
  },

  didReportLowBatteryWarning() {
    //Alert.alert('Card Reader Warning', 'The card reader battery is low.  Recharge it soon.')
  },

  // disconnectReader disconnects from the card reader, if we are connected, and
  // cancels any outstanding attempt to connect to it.  It is called when we log
  // out.
  async disconnectReader() {
    if (this.discovering) {
      try {
        await StripeTerminal.abortDiscoverReaders();
      } catch (err) {
        console.error('Error aborting discover readers: ', err.error);
      }
    }
    if (
      (await StripeTerminal.getConnectionStatus()) !==
      StripeTerminal.ConnectionStatusNotConnected
    ) {
      try {
        await StripeTerminal.disconnectReader();
        this.deviceName = '';
      } catch (err) {
        console.error('Error disconnecting reader: ', err.error);
      }
    }
    this.isConnected = false;
  },

  // retrievePaymentIntent retrieves a PaymentIntent from Stripe given its
  // secret token.
  async retrievePaymentIntent(secret) {
    try {
      const intent = await StripeTerminal.retrievePaymentIntent(secret);
      return intent;
    } catch (err) {
      console.error('Error creating payment intent', err);
      throw err.error;
    }
  },

  async createPayment(amount, currency) {
    try {
      const intent = await StripeTerminal.createPayment({
        amount: amount,
        currency: currency,
      });
      this.paymentStatus = 'done';
      return intent;
    } catch (err) {
      console.error('Error creating payment intent', err);
      throw err.error;
    }
  },

  addReaderMessageListener(f) {
    StripeTerminal.addDidRequestReaderInputListener(f);
    StripeTerminal.addDidRequestReaderDisplayMessageListener(f);
  },
  removeReaderMessageListener(f) {
    StripeTerminal.removeDidRequestReaderInputListener(f);
    StripeTerminal.removeDidRequestReaderDisplayMessageListener(f);
  },

  async collectPaymentMethod() {
    try {
      const intent = await StripeTerminal.collectPaymentMethod();
      return intent;
    } catch (err) {
      if (err.code !== 2020)
        console.error('Error collecting payment method', err);
      throw err; // whole object, not string, so we can look at code
    }
  },

  async abortCollectPaymentMethod() {
    try {
      await StripeTerminal.abortCreatePayment();
    } catch (err) {
      // log, not error, and no throw:  not a fatal problem
      console.log('Error aborting collection of payment method', err);
    }
  },

  async processPayment() {
    try {
      const intent = await StripeTerminal.processPayment();
      return intent;
    } catch (err) {
      console.error('Error processing payment', err);
      throw err;
    }
  },
};

StripeTerminal.addReadersDiscoveredListener(
  readerAPI.readersDiscovered.bind(readerAPI)
);
StripeTerminal.addDidReportUnexpectedReaderDisconnectListener(
  readerAPI.didReportUnexpectedReaderDisconnect.bind(readerAPI)
);
StripeTerminal.addDidReportLowBatteryWarningListener(
  readerAPI.didReportLowBatteryWarning.bind(readerAPI)
);

export default readerAPI;
`

this is my reader component

**Comment by HiteshR90** [comment]
@patmisch  any update on this ?

**Comment by HiteshR90** [comment]
@patmisch any update on this ?

**Comment by patmisch** [comment]
@HiteshR90 I'm not sure what is going on with your setup. We are currently using this branch in production without any problems.

**Comment by HiteshR90** [comment]
> @HiteshR90 I'm not sure what is going on with your setup. We are currently using this branch in production without any problems.

Do you have any sample code that I can try ?

**Pull request merged**
