### PR TITLE
Updated Example for mynorth's update

### PR DESCRIPTION
**Pull request by vivekvardhanadepu**
@theopolisme @dsgraham could you please review it?

### CODE REVIEW

**Comment by rissois** [comment]
This has been tremendously helpful for someone who has only worked with React Native hooks, thank you. 

Two quick questions:
1. I am assuming any location service can work in lieu of react-native-location-enabler (e.g. Expo)?
2. Is reason for setting the first parameter of StripeTerminal.discoverReaders to 1? [side note: I've never gotten simulator to actually work correctly this way without altering the RNStripeTerminal.m file (iOS); never tested Android]

**Comment by vivekvardhanadepu** [comment]
> This has been tremendously helpful for someone who has only worked with React Native hooks, thank you.
> 
> Two quick questions:
> 
> 1. I am assuming any location service can work in lieu of react-native-location-enabler (e.g. Expo)?

Yes indeed
> 2. Is reason for setting the first parameter of StripeTerminal.discoverReaders to 1? [side note: I've never gotten simulator to actually work correctly this way without altering the RNStripeTerminal.m file (iOS); never tested Android]

The first parameter is not used in the android code. So, it really doesn't mater what you set. Yes, the simulator is working perfectly fine in android

**Comment by rissois** [comment]
Thank you, unfortunately I am clearly too far out of my element here and am pausing work until I see whether I can understand the final Terminal SDK 2.0 update to the package and its docs.

**Comment by theopolisme** [comment]
Thank you!

**Comment by vivekvardhanadepu** [comment]
> Thank you, unfortunately I am clearly too far out of my element here and am pausing work until the update to Terminal SDK 2.0 is complete. Hopefully then I can understand the newest version of the docs.

it is complete right?🤔

**Pull request merged**
