### PR TITLE
Update to use Stripe terminal SDK 2

### PR DESCRIPTION
**Pull request by dsgraham**
This updates the native modules to use version 2 of Stripe's terminal SDK, required by late January 2022. It likely still needs some work related to reader firmware updates, but we've been using it in production for a couple months successfully.

### CODE REVIEW

**Comment by nabeelanjum** [comment]
Hi @theopolisme could you please review and merge this PR asap please? Really need this

**Comment by dsgraham** [comment]
> Hi @dsgraham and thanks for sharing this.
> 
> Do you happen to have a sample application showcasing the Terminal connection, payment intent, and charge operations?
> 
> Have you run into any issues in production?

I don't have an example that is publicly available, but the Javascript interface is basically the same. You do need to supply Stripe with a location when connecting to a reader now. The example code in the README is not completely accurate - I'll try and update that soon.

We have been running this for a couple months in production with no problems.

**Comment by theopolisme** [comment]
Hi all,

Looks like we are all rushing to upgrade for Stripe's new firmware upgrade requirements :)

Thank you, @dsgraham, for your work on this!!

In the short term @nabeelanjum and others, I would recommend trying to point your app to @dsgraham's fork.

I agree it would be great to merge this in ASAP. @dsgraham if you are able to share some updated example code/docs, I think that would be a huge help for folks, and with that final missing piece we can get this merged in pronto.

**Comment by JeanHules** [comment]
@dsgraham Thanks for doing this! 

So is this to handle the update BBPOS firmware update? Or is this for the Stripe SDK update? Or are they one in the same?

Also, is there a way to verify the update is happening? I am still seeing StripeTeminal 1.4 in my Podfile.

**Comment by dsgraham** [comment]
> So is this to handle the update BBPOS firmware update? Or is this for the Stripe SDK update? Or are they one in the same?
> 
> Also, is there a way to verify the update is happening? I am still seeing StripeTeminal 1.4 in my Podfile.

This is a [Stripe SDK update](https://stripe.com/docs/terminal/references/sdk-migration-guide). You should be able to update the reader firmware on the old version as well, but it work a little better using Stripe Terminal 2. The update will start automatically upon connection, triggering the `didStartInstallingUpdate` event. You can provide user feedback on the firmware update using the `didReportReaderSoftwareUpdateProgress` listener, which returns a float for % complete. Updating my test reader took about 2 minutes.

I have the following in my Podfile:
```
  pod 'StripeTerminal', '~> 2'
  pod 'RNStripeTerminal', :path => '../node_modules/react-native-stripe-terminal'
```

**Comment by peraltafederico** [comment]
Hello @dsgraham! Amazing work, thank you very much.

Does [Stripe Reader M2](https://stripe.com/docs/terminal/payments/setup-reader/stripe-m2) work with this PR?

**Comment by dsgraham** [comment]
> Hello @dsgraham! Amazing work, thank you very much.
> 
> Does [Stripe Reader M2](https://stripe.com/docs/terminal/payments/setup-reader/stripe-m2) work with this PR?

I think it should. I just got an M2 last week and haven't tried it out yet.

**Comment by peraltafederico** [comment]
Awesome @dsgraham! I'll get an M2 in the next weeks and I'll try it out.

Let me know if it worked when you have tested it! :) 

Thanks again!

**Comment by vivekvardhanadepu** [comment]
for those of you who are looking for updated example: https://github.com/theopolisme/react-native-stripe-terminal/pull/64

**Pull request merged**
